[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "sdl3_audio"
version = "0.1.0"
readme = "README.md"

[tool.setuptools.packages.find]
where = ["./src"]
