 # This file is auto generated
import ctypes
import typing

def load_sdl3_dll(sdl_dll_path:str) -> SDL3DLL:...

SDL_PropertiesID:typing.TypeAlias=ctypes.c_uint32

class SDL_Semaphore(ctypes.Structure):
    _fields_ = [ # type: ignore
    ]

SDL_AudioDeviceID:typing.TypeAlias=ctypes.c_uint32
SDL_AUDIO_DEVICE_DEFAULT_PLAYBACK=SDL_AudioDeviceID(4294967295)
SDL_AUDIO_DEVICE_DEFAULT_RECORDING=SDL_AudioDeviceID(4294967294)
SDL_AudioFormat:typing.TypeAlias=ctypes.c_uint16
SDL_AUDIO_UNKNOWN=SDL_AudioFormat(0)
SDL_AUDIO_U8=SDL_AudioFormat(8)
SDL_AUDIO_S8=SDL_AudioFormat(32776)
SDL_AUDIO_S16LE=SDL_AudioFormat(32784)
SDL_AUDIO_S16BE=SDL_AudioFormat(36880)
SDL_AUDIO_S32LE=SDL_AudioFormat(32800)
SDL_AUDIO_S32BE=SDL_AudioFormat(36896)
SDL_AUDIO_F32LE=SDL_AudioFormat(33056)
SDL_AUDIO_F32BE=SDL_AudioFormat(37152)

class SDL_AudioSpec(ctypes.Structure):
    format:int
    channels:int
    freq:int
    _fields_ = [ # type: ignore
        ("format",SDL_AudioFormat),
        ("channels",ctypes.c_int),
        ("freq",ctypes.c_int),
    ]


class SDL_AudioStream(ctypes.Structure):
    _fields_ = [ # type: ignore
    ]

if typing.TYPE_CHECKING:
    SDL_AudioStreamCallback:typing.TypeAlias=ctypes._FuncPointer
else:
    SDL_AudioStreamCallback=ctypes.CFUNCTYPE(None, ctypes.POINTER(None), ctypes.POINTER(SDL_AudioStream), ctypes.c_int, ctypes.c_int)
SDL_InitFlags:typing.TypeAlias=ctypes.c_uint32
SDL_INIT_AUDIO=SDL_InitFlags(16)

class SDL3DLL(ctypes.CDLL):
    def SDL_free(self,mem:ctypes._Pointer,)->None:...
    def SDL_SetPointerProperty(self,props:SDL_PropertiesID,name:ctypes.c_char_p,value:ctypes._Pointer[None],)->bool:...
    def SDL_GetPointerProperty(self,props:SDL_PropertiesID,name:ctypes.c_char_p,default_value:ctypes._Pointer[None],)->ctypes._Pointer[None]:...
    def SDL_CreateSemaphore(self,initial_value:ctypes.c_uint32,)->ctypes._Pointer[SDL_Semaphore]:...
    def SDL_DestroySemaphore(self,sem:ctypes._Pointer[SDL_Semaphore],)->None:...
    def SDL_WaitSemaphoreTimeout(self,sem:ctypes._Pointer[SDL_Semaphore],timeoutMS:ctypes.c_int32,)->bool:...
    def SDL_SignalSemaphore(self,sem:ctypes._Pointer[SDL_Semaphore],)->None:...
    def SDL_GetSemaphoreValue(self,sem:ctypes._Pointer[SDL_Semaphore],)->int:...
    def SDL_GetNumAudioDrivers(self,)->int:...
    def SDL_GetAudioDriver(self,index:ctypes.c_int,)->bytes|None:...
    def SDL_GetCurrentAudioDriver(self,)->bytes|None:...
    def SDL_GetAudioRecordingDevices(self,count:ctypes._Pointer[ctypes.c_int],)->ctypes._Pointer[SDL_AudioDeviceID]:...
    def SDL_GetAudioPlaybackDevices(self,count:ctypes._Pointer[ctypes.c_int],)->ctypes._Pointer[SDL_AudioDeviceID]:...
    def SDL_GetAudioDeviceName(self,devid:SDL_AudioDeviceID,)->bytes|None:...
    def SDL_GetAudioDeviceFormat(self,devid:SDL_AudioDeviceID,spec:ctypes._Pointer[SDL_AudioSpec],sample_frames:ctypes._Pointer[ctypes.c_int],)->bool:...
    def SDL_OpenAudioDevice(self,devid:SDL_AudioDeviceID,spec:ctypes._Pointer[SDL_AudioSpec],)->int:...
    def SDL_PauseAudioDevice(self,devid:SDL_AudioDeviceID,)->bool:...
    def SDL_ResumeAudioDevice(self,devid:SDL_AudioDeviceID,)->bool:...
    def SDL_AudioDevicePaused(self,devid:SDL_AudioDeviceID,)->bool:...
    def SDL_GetAudioDeviceGain(self,devid:SDL_AudioDeviceID,)->float:...
    def SDL_SetAudioDeviceGain(self,devid:SDL_AudioDeviceID,gain:ctypes.c_float,)->bool:...
    def SDL_CloseAudioDevice(self,devid:SDL_AudioDeviceID,)->None:...
    def SDL_BindAudioStream(self,devid:SDL_AudioDeviceID,stream:ctypes._Pointer[SDL_AudioStream],)->bool:...
    def SDL_UnbindAudioStream(self,stream:ctypes._Pointer[SDL_AudioStream],)->None:...
    def SDL_GetAudioStreamDevice(self,stream:ctypes._Pointer[SDL_AudioStream],)->int:...
    def SDL_CreateAudioStream(self,src_spec:ctypes._Pointer[SDL_AudioSpec],dst_spec:ctypes._Pointer[SDL_AudioSpec],)->ctypes._Pointer[SDL_AudioStream]:...
    def SDL_GetAudioStreamProperties(self,stream:ctypes._Pointer[SDL_AudioStream],)->int:...
    def SDL_GetAudioStreamFormat(self,stream:ctypes._Pointer[SDL_AudioStream],src_spec:ctypes._Pointer[SDL_AudioSpec],dst_spec:ctypes._Pointer[SDL_AudioSpec],)->bool:...
    def SDL_SetAudioStreamFormat(self,stream:ctypes._Pointer[SDL_AudioStream],src_spec:ctypes._Pointer[SDL_AudioSpec],dst_spec:ctypes._Pointer[SDL_AudioSpec],)->bool:...
    def SDL_GetAudioStreamGain(self,stream:ctypes._Pointer[SDL_AudioStream],)->float:...
    def SDL_SetAudioStreamGain(self,stream:ctypes._Pointer[SDL_AudioStream],gain:ctypes.c_float,)->bool:...
    def SDL_GetAudioStreamFrequencyRatio(self,stream:ctypes._Pointer[SDL_AudioStream],)->float:...
    def SDL_SetAudioStreamFrequencyRatio(self,stream:ctypes._Pointer[SDL_AudioStream],ratio:ctypes.c_float,)->bool:...
    def SDL_PutAudioStreamData(self,stream:ctypes._Pointer[SDL_AudioStream],buf:ctypes._Pointer,len:ctypes.c_int,)->bool:...
    def SDL_GetAudioStreamData(self,stream:ctypes._Pointer[SDL_AudioStream],buf:ctypes._Pointer,len:ctypes.c_int,)->int:...
    def SDL_GetAudioStreamAvailable(self,stream:ctypes._Pointer[SDL_AudioStream],)->int:...
    def SDL_GetAudioStreamQueued(self,stream:ctypes._Pointer[SDL_AudioStream],)->int:...
    def SDL_FlushAudioStream(self,stream:ctypes._Pointer[SDL_AudioStream],)->bool:...
    def SDL_ClearAudioStream(self,stream:ctypes._Pointer[SDL_AudioStream],)->bool:...
    def SDL_SetAudioStreamGetCallback(self,stream:ctypes._Pointer[SDL_AudioStream],callback:SDL_AudioStreamCallback,userdata:ctypes._Pointer,)->bool:...
    def SDL_SetAudioStreamPutCallback(self,stream:ctypes._Pointer[SDL_AudioStream],callback:SDL_AudioStreamCallback,userdata:ctypes._Pointer,)->bool:...
    def SDL_DestroyAudioStream(self,stream:ctypes._Pointer[SDL_AudioStream],)->None:...
    def SDL_LoadWAV(self,path:ctypes.c_char_p,spec:ctypes._Pointer[SDL_AudioSpec],audio_buf:ctypes._Pointer[ctypes._Pointer[ctypes.c_uint8]],audio_len:ctypes._Pointer[ctypes.c_uint32],)->bool:...
    def SDL_MixAudio(self,dst:ctypes._Pointer[ctypes.c_uint8],src:ctypes._Pointer[ctypes.c_uint8],format:SDL_AudioFormat,len:ctypes.c_uint32,volume:ctypes.c_float,)->bool:...
    def SDL_ConvertAudioSamples(self,src_spec:ctypes._Pointer[SDL_AudioSpec],src_data:ctypes._Pointer[ctypes.c_uint8],src_len:ctypes.c_int,dst_spec:ctypes._Pointer[SDL_AudioSpec],dst_data:ctypes._Pointer[ctypes._Pointer[ctypes.c_uint8]],dst_len:ctypes._Pointer[ctypes.c_int],)->bool:...
    def SDL_GetError(self,)->bytes|None:...
    def SDL_Init(self,flags:SDL_InitFlags,)->bool:...
    def SDL_WasInit(self,flags:SDL_InitFlags,)->int:...
    def SDL_Quit(self,)->None:...

